/*
2875. Minimum Size Subarray in Infinite Array

You are given a 0-indexed array nums and an integer target.

A 0-indexed array infinite_nums is generated by infinitely appending the elements of nums to itself.

Return the length of the shortest subarray of the array infinite_nums with a sum equal to target. If there is no such subarray return -1.

 

Example 1:

Input: nums = [1,2,3], target = 5
Output: 2
Explanation: In this example infinite_nums = [1,2,3,1,2,3,1,2,...].
The subarray in the range [1,2], has the sum equal to target = 5 and length = 2.
It can be proven that 2 is the shortest length of a subarray with sum equal to target = 5.
Example 2:

Input: nums = [1,1,1,2,3], target = 4
Output: 2
Explanation: In this example infinite_nums = [1,1,1,2,3,1,1,1,2,3,1,1,...].
The subarray in the range [4,5], has the sum equal to target = 4 and length = 2.
It can be proven that 2 is the shortest length of a subarray with sum equal to target = 4.
Example 3:

Input: nums = [2,4,6,8], target = 3
Output: -1
Explanation: In this example infinite_nums = [2,4,6,8,2,4,6,8,...].
It can be proven that there is no subarray with sum equal to target = 3.
 

Constraints:

1 <= nums.length <= 105
1 <= nums[i] <= 105
1 <= target <= 109
*/

/*
🧠 Intuition Summary

We want the minimum length subarray (possibly circular) whose sum equals target.

🔑 Core Observation

The array can be reused infinitely, so:

target = (full arrays) + (remaining sum)
💡 Break the Problem

Let:

total = sum of nums

Then:

target = k * total + remainder

k = target / total → full array repeats

remainder = target % total → need to find this

🎯 Strategy

Take k full arrays → contributes:

k * n elements

Now problem reduces to:

Find shortest subarray (circular) with sum = remainder
🔄 Handling Circular Array

Instead of actual circular logic:

Traverse array twice → simulate circular behavior

👉 Use r % n

🧠 Why Sliding Window Works

Because:

All nums are positive

👉 So:

Expanding window increases sum

Shrinking window decreases sum

🎯 Final Answer
answer = (k * n) + (min subarray length for remainder)

If no such subarray:

return -1
⚡ Edge Case
If remainder == 0:
→ Just return k * n
🧠 One-Line Intuition
Break target into full array cycles + leftover,
then find smallest subarray (in circular array) that gives leftover.
*/

class Solution {
    public int minSizeSubarray(int[] nums, int target) 
    {
        int total = 0;
        int n = nums.length;

        for(int i: nums) total += i;

        int sum = target % total;
        int times = target / total;

        if(sum == 0 && times > 0) return times*n;

        int l = 0, r = 0;
        int ans = Integer.MAX_VALUE;
        int cur_sum = 0;
        while(r < 2*n)
        {
            cur_sum += nums[r%n];
            if(cur_sum < sum) r++;
            else if (cur_sum == sum)
            {
                ans = Math.min(ans, r-l+1);
                r++;
            }
            else
            {
                while(cur_sum >= sum && l <= r)
                {
                    if(cur_sum == sum) ans = Math.min(ans, r-l+1);
                    cur_sum -= nums[l%n];
                    l++;
                }
                r++;
            }
        }
        if(ans == Integer.MAX_VALUE) return -1;
        return times*n + ans;
    }
}